"""Ghostscript-backed EPS rendering and atomic PNG export.

Ghostscript is the only EPS/PostScript parser used here. Every render job owns
its subprocess and output path, so preview and export workers can safely use one
``EpsRenderer`` instance at the same time.
"""

from __future__ import annotations

import math
import os
import re
import shutil
import subprocess
import tempfile
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol, runtime_checkable

from config import find_ghostscript


MIN_DPI = 72
MAX_DPI = 600
DEFAULT_DPI = 300
MAX_EXPORT_PIXELS = 64_000_000
MAX_EXPORT_EDGE = 30_000
_HEX_COLOR = re.compile(r"^#[0-9A-Fa-f]{6}$")
_PAGE_SIZE_NUMBER = r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?"
_PAGE_SIZE_LINE = re.compile(
    rf"^%%PageSize:\s*\[\s*({_PAGE_SIZE_NUMBER})\s+({_PAGE_SIZE_NUMBER})\s*\]\s*$",
    re.MULTILINE,
)


@runtime_checkable
class _CancellationEvent(Protocol):
    """The small part of ``threading.Event`` used by the renderer."""

    def is_set(self) -> bool: ...


class GhostscriptNotFoundError(RuntimeError):
    """Raised when the configured Ghostscript console program is unavailable."""


class EpsFileBusyError(RuntimeError):
    """Raised after an EPS file remains unreadable during the retry window."""


class EpsRenderError(RuntimeError):
    """Raised when Ghostscript reports that it could not render the EPS file."""


class EpsRenderCancelledError(EpsRenderError):
    """Raised when a preview or export render is explicitly cancelled."""


class PngExportError(RuntimeError):
    """Raised when a rendered image cannot be written as the requested PNG."""


@dataclass(frozen=True)
class RenderResult:
    """A successful render result stored in the session-only cache."""

    source: Path
    png_path: Path
    dpi: int
    rendered_at: float


@dataclass(frozen=True)
class PdfRenderResult:
    """A vector PDF preview stored in the session-only cache."""

    source: Path
    pdf_path: Path
    converted_at: float


class RenderCache:
    """Own a private temporary directory and remove it when the app exits."""

    def __init__(self) -> None:
        self.directory = Path(tempfile.mkdtemp(prefix="eps_live_viewer_"))
        self._sequence = 0
        self._lock = threading.Lock()

    def next_path(self, suffix: str = ".png") -> Path:
        """Reserve a unique cache path (the caller creates its contents)."""
        normalised_suffix = suffix if suffix.startswith(".") else f".{suffix}"
        if normalised_suffix.lower() not in {".png", ".pdf", ".eps"}:
            raise ValueError("缓存文件类型必须是 PNG、PDF 或 EPS。")
        with self._lock:
            self._sequence += 1
            return self.directory / f"render_{self._sequence:06d}{normalised_suffix.lower()}"

    def release(self, path: Path | None) -> None:
        if path is None:
            return
        try:
            path.unlink(missing_ok=True)
        except OSError:
            # Qt may still be reading an image during window teardown. The
            # session directory cleanup gets another opportunity later.
            pass

    def cleanup(self) -> None:
        # All children of this private directory are generated by this object.
        try:
            children = list(self.directory.iterdir())
        except OSError:
            return
        for item in children:
            if item.is_file():
                try:
                    item.unlink(missing_ok=True)
                except OSError:
                    # One QtPdf handle should not prevent removal of every other
                    # independent cache entry.
                    pass
        try:
            self.directory.rmdir()
        except OSError:
            pass


class EpsRenderer:
    """Convert EPS files with Ghostscript's alpha-capable PNG device.

    ``dpi`` in the constructor and :meth:`set_dpi` remain for source
    compatibility with older callers. New code should always pass ``dpi`` to
    :meth:`render`; no in-flight job reads mutable renderer DPI state.
    """

    def __init__(self, ghostscript_path: str = "", dpi: int = DEFAULT_DPI) -> None:
        self._settings_lock = threading.Lock()
        self._configured_ghostscript_path = ghostscript_path
        self._default_dpi = self._validated_dpi(dpi)
        self.cache = RenderCache()

    @staticmethod
    def _validated_dpi(dpi: int) -> int:
        if isinstance(dpi, bool) or not isinstance(dpi, int):
            raise ValueError("DPI 必须是整数。")
        if not MIN_DPI <= dpi <= MAX_DPI:
            raise ValueError(f"DPI 必须在 {MIN_DPI} 到 {MAX_DPI} 之间。")
        return dpi

    @property
    def dpi(self) -> int:
        """Legacy default DPI; explicit per-job DPI is preferred."""
        with self._settings_lock:
            return self._default_dpi

    @dpi.setter
    def dpi(self, value: int) -> None:
        self.set_dpi(value)

    @property
    def ghostscript_path(self) -> Path | None:
        with self._settings_lock:
            configured = self._configured_ghostscript_path
        return find_ghostscript(configured)

    def set_ghostscript_path(self, path: str) -> None:
        """Set the path used by jobs that start after this call."""
        with self._settings_lock:
            self._configured_ghostscript_path = path.strip()

    def set_dpi(self, dpi: int) -> None:
        """Set only the legacy default for calls that omit ``dpi``."""
        validated = self._validated_dpi(dpi)
        with self._settings_lock:
            self._default_dpi = validated

    @staticmethod
    def _raise_if_cancelled(cancel_event: _CancellationEvent | None) -> None:
        if cancel_event and cancel_event.is_set():
            raise EpsRenderCancelledError("渲染已取消")

    def _snapshot_source(
        self,
        source: Path,
        cancel_event: _CancellationEvent | None,
        timeout_seconds: float = 5.0,
        retry_seconds: float = 0.2,
    ) -> Path:
        """Copy a stable EPS generation into the private session cache.

        Scientific programs commonly truncate and rewrite a file in place.  A
        successful open alone does not prove that writing has finished, so the
        size/mtime signature is checked before and after a complete copy.  The
        Ghostscript process always reads this immutable snapshot.
        """
        deadline = time.monotonic() + timeout_seconds
        last_error: OSError | None = None
        while time.monotonic() < deadline:
            self._raise_if_cancelled(cancel_event)
            snapshot = self.cache.next_path(".eps")
            try:
                before = source.stat()
                if before.st_size <= 0:
                    raise OSError("EPS/PS 文件为空")
                with source.open("rb") as source_file, snapshot.open("wb") as output_file:
                    shutil.copyfileobj(source_file, output_file, length=1024 * 1024)
                    output_file.flush()
                after = source.stat()
                copied_size = snapshot.stat().st_size
                before_signature = (before.st_mtime_ns, before.st_size)
                after_signature = (after.st_mtime_ns, after.st_size)
                if before_signature == after_signature and copied_size == after.st_size:
                    return snapshot
                last_error = OSError("EPS/PS 文件仍在写入")
            except OSError as error:
                last_error = error
            self.cache.release(snapshot)
            if isinstance(cancel_event, threading.Event):
                if cancel_event.wait(retry_seconds):
                    raise EpsRenderCancelledError("渲染已取消")
            else:
                time.sleep(retry_seconds)
        detail = str(last_error) if last_error else "文件不可读"
        raise EpsFileBusyError(f"EPS/PS 文件暂时不可读：{detail}")

    @staticmethod
    def _tail(text: str, maximum: int = 1_500) -> str:
        text = " ".join(text.split())
        return text[-maximum:] if len(text) > maximum else text

    @staticmethod
    def _stop_process(process: subprocess.Popen[str]) -> None:
        try:
            process.terminate()
            process.wait(timeout=2)
        except (OSError, subprocess.TimeoutExpired):
            try:
                process.kill()
                process.wait(timeout=2)
            except (OSError, subprocess.TimeoutExpired):
                pass

    def _run_ghostscript(
        self,
        command: list[str],
        output_path: Path,
        cancel_event: _CancellationEvent | None,
        failure_message: str,
    ) -> None:
        """Run one isolated Ghostscript job and validate its output."""
        try:
            returncode, stdout, stderr = self._capture_ghostscript(
                command,
                cancel_event,
            )
        except Exception:
            self.cache.release(output_path)
            raise

        if (
            returncode != 0
            or not output_path.is_file()
            or output_path.stat().st_size == 0
        ):
            self.cache.release(output_path)
            detail = self._tail(stderr or stdout)
            suffix = f"\nGhostscript: {detail}" if detail else ""
            raise EpsRenderError(f"{failure_message}{suffix}")

    def _capture_ghostscript(
        self,
        command: list[str],
        cancel_event: _CancellationEvent | None,
    ) -> tuple[int, str, str]:
        """Run Ghostscript while draining both pipes and honoring cancellation."""
        process: subprocess.Popen[str] | None = None
        stdout = ""
        stderr = ""
        try:
            process = subprocess.Popen(
                command,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                encoding="utf-8",
                errors="replace",
                creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
            )
            # communicate(timeout=...) drains both pipes while allowing regular
            # cancellation checks.  Polling first and reading afterwards can
            # deadlock when verbose Ghostscript output fills an OS pipe buffer.
            while True:
                if cancel_event and cancel_event.is_set():
                    self._stop_process(process)
                    raise EpsRenderCancelledError("渲染已取消")
                try:
                    stdout, stderr = process.communicate(timeout=0.1)
                    break
                except subprocess.TimeoutExpired:
                    continue
        except EpsRenderCancelledError:
            raise
        except OSError as error:
            if process is not None and process.poll() is None:
                self._stop_process(process)
            raise EpsRenderError(f"无法启动 Ghostscript：{error}") from error
        return process.returncode, stdout, stderr

    @staticmethod
    def _parse_page_sizes_points(output: str) -> list[tuple[float, float]]:
        """Parse page-size pairs printed by Ghostscript's EndPage callback."""
        page_sizes: list[tuple[float, float]] = []
        for match in _PAGE_SIZE_LINE.finditer(output.replace("\r\n", "\n")):
            width = float(match.group(1))
            height = float(match.group(2))
            if (
                math.isfinite(width)
                and math.isfinite(height)
                and width > 0
                and height > 0
            ):
                page_sizes.append((width, height))
        if not page_sizes:
            raise PngExportError(
                "Ghostscript 无法确定 EPS 页面尺寸，已取消 PNG 导出。"
            )
        return page_sizes

    def _guard_png_dimensions(
        self,
        snapshot: Path,
        executable: Path,
        dpi: int,
        cancel_event: _CancellationEvent | None,
        crop_to_eps_bounds: bool,
    ) -> None:
        """Reject oversized pages before starting the pngalpha device.

        ``bbox`` reports painted marks and can miss a huge empty page margin.
        An EndPage callback instead asks Ghostscript for each effective
        ``PageSize`` after it has interpreted the input. EPS files additionally
        use their DSC bounding box as the page crop; ordinary PS files keep
        their PostScript page size.
        """
        end_page_callback = (
            "<</EndPage { pop pop (%%PageSize:) print "
            "currentpagedevice /PageSize get == flush true } bind>> setpagedevice"
        )
        command = [
            str(executable),
            "-q",
            "-dSAFER",
            "-dBATCH",
            "-dNOPAUSE",
            "-dFirstPage=1",
            "-dLastPage=1",
            *(["-dEPSCrop"] if crop_to_eps_bounds else []),
            "-sDEVICE=nullpage",
            "-c",
            end_page_callback,
            "-f",
            str(snapshot),
        ]
        returncode, stdout, stderr = self._capture_ghostscript(command, cancel_event)
        combined_output = f"{stdout}\n{stderr}"
        if returncode != 0:
            detail = self._tail(stderr or stdout)
            suffix = f"\nGhostscript: {detail}" if detail else ""
            raise PngExportError(f"Ghostscript 无法检测 EPS 页面尺寸。{suffix}")

        for page_width, page_height in self._parse_page_sizes_points(combined_output):
            # Add two pixels for device rounding/antialiasing at cropped edges.
            pixel_width = math.ceil(page_width * dpi / 72.0) + 2
            pixel_height = math.ceil(page_height * dpi / 72.0) + 2
            if (
                pixel_width > MAX_EXPORT_EDGE
                or pixel_height > MAX_EXPORT_EDGE
                or pixel_width * pixel_height > MAX_EXPORT_PIXELS
            ):
                raise PngExportError(
                    f"PNG 预计尺寸为 {pixel_width} × {pixel_height} 像素，"
                    "可能耗尽内存；请降低导出 DPI。"
                )

    def render(
        self,
        source: str | Path,
        dpi: int | _CancellationEvent | None = None,
        cancel_event: _CancellationEvent | None = None,
        crop_to_eps_bounds: bool | None = None,
        guard_dimensions: bool = False,
    ) -> RenderResult:
        """Render one EPS or PS file into a new transparent PNG cache file.

        ``render(source, old_cancel_event)`` is accepted for compatibility. In
        new code use ``render(source, dpi=600, cancel_event=event)``.
        """
        # The old public signature used its second positional argument for the
        # cancellation event. Preserve it while preferring explicit per-job DPI.
        if dpi is not None and not isinstance(dpi, int):
            if cancel_event is not None or not isinstance(dpi, _CancellationEvent):
                raise TypeError("dpi 必须是整数，cancel_event 必须支持 is_set()。")
            cancel_event = dpi
            dpi = None

        if dpi is None:
            with self._settings_lock:
                job_dpi = self._default_dpi
        else:
            job_dpi = self._validated_dpi(dpi)

        source_path = Path(source).resolve()
        if not source_path.is_file():
            raise FileNotFoundError(f"找不到 EPS/PS 文件：{source_path}")

        executable = self.ghostscript_path
        if executable is None:
            raise GhostscriptNotFoundError(
                "未找到 Ghostscript，请安装 Ghostscript 或在设置中指定路径。"
            )

        if crop_to_eps_bounds is None:
            crop_to_eps_bounds = source_path.suffix.lower() == ".eps"

        snapshot = self._snapshot_source(source_path, cancel_event)
        png_path = self.cache.next_path()
        command = [
            str(executable),
            "-dSAFER",
            "-dBATCH",
            "-dNOPAUSE",
            "-dFirstPage=1",
            "-dLastPage=1",
            *(["-dEPSCrop"] if crop_to_eps_bounds else []),
            "-sDEVICE=pngalpha",
            f"-r{job_dpi}",
            f"-sOutputFile={png_path}",
            str(snapshot),
        ]
        try:
            if guard_dimensions:
                self._guard_png_dimensions(
                    snapshot,
                    executable,
                    job_dpi,
                    cancel_event,
                    crop_to_eps_bounds,
                )
            self._run_ghostscript(
                command,
                png_path,
                cancel_event,
                "EPS/PS 文件无法解析或渲染失败。",
            )
        finally:
            self.cache.release(snapshot)

        return RenderResult(source_path, png_path, job_dpi, time.time())

    def convert_to_pdf(
        self,
        source: str | Path,
        cancel_event: _CancellationEvent | None = None,
    ) -> PdfRenderResult:
        """Convert one EPS or PS file to a vector PDF preview cache.

        Ghostscript's ``pdfwrite`` device preserves vector paths and text where
        possible. The result can be displayed by QtPdf, which rerenders pages at
        the current zoom instead of magnifying a fixed-DPI bitmap.
        """
        source_path = Path(source).resolve()
        if not source_path.is_file():
            raise FileNotFoundError(f"找不到 EPS/PS 文件：{source_path}")

        executable = self.ghostscript_path
        if executable is None:
            raise GhostscriptNotFoundError(
                "未找到 Ghostscript，请安装 Ghostscript 或在设置中指定路径。"
            )

        crop_to_eps_bounds = source_path.suffix.lower() == ".eps"

        snapshot = self._snapshot_source(source_path, cancel_event)
        pdf_path = self.cache.next_path(".pdf")
        command = [
            str(executable),
            "-dSAFER",
            "-dBATCH",
            "-dNOPAUSE",
            "-dFirstPage=1",
            "-dLastPage=1",
            *(["-dEPSCrop"] if crop_to_eps_bounds else []),
            "-sDEVICE=pdfwrite",
            "-dCompatibilityLevel=1.7",
            f"-sOutputFile={pdf_path}",
            str(snapshot),
        ]
        try:
            self._run_ghostscript(
                command,
                pdf_path,
                cancel_event,
                "EPS/PS 文件无法解析或转换为 PDF。",
            )
        finally:
            self.cache.release(snapshot)
        return PdfRenderResult(source_path, pdf_path, time.time())

    @staticmethod
    def _normalise_export_path(target: str | Path) -> Path:
        path = Path(target).expanduser()
        if path.name in ("", ".", ".."):
            raise PngExportError("PNG 输出文件名无效。")
        if path.suffix.lower() != ".png":
            path = path.with_suffix(".png")
        return path.resolve()

    @staticmethod
    def _validate_background(mode: str, color: str) -> tuple[str, str]:
        normalised_mode = mode.strip().lower()
        if normalised_mode not in {"transparent", "white", "custom"}:
            raise ValueError("背景模式必须是 transparent、white 或 custom。")
        if normalised_mode == "white":
            return normalised_mode, "#FFFFFF"
        if normalised_mode == "custom" and not _HEX_COLOR.fullmatch(color.strip()):
            raise ValueError("自定义背景颜色必须使用 #RRGGBB 格式。")
        return normalised_mode, color.strip().upper()

    def export_png(
        self,
        source: str | Path,
        target: str | Path,
        dpi: int = DEFAULT_DPI,
        background: str = "transparent",
        background_color: str = "#FFFFFF",
        cancel_event: _CancellationEvent | None = None,
    ) -> Path:
        """Render and atomically export an EPS or PS file as PNG.

        The EPS is first rendered as ``pngalpha``. White/custom backgrounds are
        composited afterwards, preserving identical geometry for all modes.
        The destination is replaced only after a complete PNG has been written.
        """
        job_dpi = self._validated_dpi(dpi)
        mode, color = self._validate_background(background, background_color)
        destination = self._normalise_export_path(target)

        try:
            destination.parent.mkdir(parents=True, exist_ok=True)
        except OSError as error:
            raise PngExportError(f"无法创建输出目录：{error}") from error
        if not destination.parent.is_dir():
            raise PngExportError("PNG 输出目录无效。")

        executable = self.ghostscript_path
        if executable is None:
            raise GhostscriptNotFoundError(
                "未找到 Ghostscript，请安装 Ghostscript 或在设置中指定路径。"
            )

        export_snapshot: Path | None = None
        render_result: RenderResult | None = None
        temporary_path: Path | None = None
        try:
            # Guard and pngalpha must see the same immutable generation. This
            # also prevents an in-place source rewrite between the page-size
            # check and rasterization from bypassing the pixel budget.
            source_path = Path(source).resolve()
            if not source_path.is_file():
                raise FileNotFoundError(f"找不到 EPS/PS 文件：{source_path}")
            export_snapshot = self._snapshot_source(source_path, cancel_event)
            crop_to_eps_bounds = source_path.suffix.lower() == ".eps"
            self._guard_png_dimensions(
                export_snapshot,
                executable,
                job_dpi,
                cancel_event,
                crop_to_eps_bounds,
            )
            render_result = self.render(
                export_snapshot,
                dpi=job_dpi,
                cancel_event=cancel_event,
                crop_to_eps_bounds=crop_to_eps_bounds,
            )
            self._raise_if_cancelled(cancel_event)

            # QImage is reentrant and safe in worker threads. Import lazily so
            # renderer diagnostics can run before a QApplication exists.
            from PyQt6.QtGui import QColor, QImage, QImageReader, QPainter

            reader = QImageReader(str(render_result.png_path), b"PNG")
            image_size = reader.size()
            if (
                not image_size.isValid()
                or image_size.width() > MAX_EXPORT_EDGE
                or image_size.height() > MAX_EXPORT_EDGE
                or image_size.width() * image_size.height() > MAX_EXPORT_PIXELS
            ):
                raise PngExportError(
                    "PNG 像素尺寸过大，可能耗尽内存；请降低导出 DPI。"
                )
            source_image = reader.read()
            if source_image.isNull():
                raise PngExportError("Ghostscript 输出的 PNG 无法读取。")

            image_to_save = source_image
            if mode != "transparent":
                composed = QImage(source_image.size(), QImage.Format.Format_ARGB32)
                composed.fill(QColor(color))
                painter = QPainter(composed)
                painter.drawImage(0, 0, source_image)
                painter.end()
                image_to_save = composed

            # QImage composition creates a fresh image and otherwise drops the
            # physical-resolution metadata written by Ghostscript.  Preserve an
            # explicit DPI value for scientific publishing/layout software.
            dots_per_meter = max(1, round(job_dpi / 0.0254))
            image_to_save.setDotsPerMeterX(dots_per_meter)
            image_to_save.setDotsPerMeterY(dots_per_meter)

            self._raise_if_cancelled(cancel_event)
            try:
                with tempfile.NamedTemporaryFile(
                    mode="wb",
                    prefix=f".{destination.stem}_",
                    suffix=".png",
                    dir=destination.parent,
                    delete=False,
                ) as temporary:
                    temporary_path = Path(temporary.name)
            except OSError as error:
                raise PngExportError(f"无法创建临时输出文件：{error}") from error

            if not image_to_save.save(str(temporary_path), "PNG"):
                raise PngExportError("PNG 编码或写入失败。")
            if temporary_path.stat().st_size == 0:
                raise PngExportError("PNG 写入失败：输出文件为空。")
            self._raise_if_cancelled(cancel_event)
            try:
                os.replace(temporary_path, destination)
            except OSError as error:
                raise PngExportError(f"无法保存 PNG 文件：{error}") from error
            temporary_path = None
            return destination
        finally:
            if temporary_path is not None:
                try:
                    temporary_path.unlink(missing_ok=True)
                except OSError:
                    pass
            if render_result is not None:
                self.cache.release(render_result.png_path)
            if export_snapshot is not None:
                self.cache.release(export_snapshot)
